name: doc_writer
description: A Flutter mobile app to write a document or letter, then print or save it as a PDF. Supports Hindi / Devanagari text.
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
