import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/doc.dart';

/// Turns a [Doc] into a PDF and hands it to the platform to print or share.
///
/// The bundled Noto Sans fonts let documents contain Hindi / Devanagari text:
/// Noto Sans covers Latin, and Noto Sans Devanagari is registered as a font
/// fallback so Devanagari glyphs resolve automatically.
class PdfService {
  pw.ThemeData? _theme;

  Future<pw.ThemeData> _loadTheme() async {
    if (_theme != null) return _theme!;
    final pw.Font latin =
        pw.Font.ttf(await rootBundle.load('assets/fonts/NotoSans-Regular.ttf'));
    final pw.Font latinBold =
        pw.Font.ttf(await rootBundle.load('assets/fonts/NotoSans-Bold.ttf'));
    final pw.Font devanagari = pw.Font
        .ttf(await rootBundle.load('assets/fonts/NotoSansDevanagari-Regular.ttf'));
    final pw.Font devanagariBold = pw.Font
        .ttf(await rootBundle.load('assets/fonts/NotoSansDevanagari-Bold.ttf'));

    _theme = pw.ThemeData.withFont(
      base: latin,
      bold: latinBold,
      fontFallback: <pw.Font>[devanagari, devanagariBold],
    );
    return _theme!;
  }

  Future<Uint8List> buildPdf(Doc doc) async {
    final pw.ThemeData theme = await _loadTheme();
    final pw.Document pdf = pw.Document(theme: theme);
    if (doc.isLetter) {
      _addLetterPage(pdf, doc, theme);
    } else {
      _addPlainPage(pdf, doc, theme);
    }
    return pdf.save();
  }

  void _addPlainPage(pw.Document pdf, Doc doc, pw.ThemeData theme) {
    pdf.addPage(
      pw.MultiPage(
        theme: theme,
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        build: (pw.Context context) => <pw.Widget>[
          pw.Header(level: 0, text: doc.displayTitle),
          pw.SizedBox(height: 12),
          ..._paragraphs(doc.body),
          pw.SizedBox(height: 24),
          _footer(),
        ],
      ),
    );
  }

  void _addLetterPage(pw.Document pdf, Doc doc, pw.ThemeData theme) {
    final String dateText = doc.letterDate;
    const pw.TextStyle body = pw.TextStyle(fontSize: 12, lineSpacing: 2);
    const pw.TextStyle bold =
        pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold);

    pdf.addPage(
      pw.MultiPage(
        theme: theme,
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(48, 48, 48, 48),
        build: (pw.Context context) => <pw.Widget>[
          if (doc.senderName.trim().isNotEmpty) pw.Text(doc.senderName.trim(), style: bold),
          if (doc.senderAddress.trim().isNotEmpty) pw.Text(doc.senderAddress.trim(), style: body),
          pw.SizedBox(height: 16),
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Text(dateText, style: body),
          ),
          pw.SizedBox(height: 16),
          if (doc.recipientName.trim().isNotEmpty) pw.Text(doc.recipientName.trim(), style: body),
          if (doc.recipientAddress.trim().isNotEmpty) pw.Text(doc.recipientAddress.trim(), style: body),
          pw.SizedBox(height: 20),
          if (doc.subject.trim().isNotEmpty)
            pw.Text('Subject: ${doc.subject.trim()}', style: bold),
          pw.SizedBox(height: 16),
          if (doc.salutation.trim().isNotEmpty) pw.Text(doc.salutation.trim(), style: body),
          pw.SizedBox(height: 8),
          ..._paragraphs(doc.body),
          pw.SizedBox(height: 24),
          if (doc.closing.trim().isNotEmpty) pw.Text(doc.closing.trim(), style: body),
          pw.SizedBox(height: 28),
          if (doc.senderName.trim().isNotEmpty) pw.Text(doc.senderName.trim(), style: bold),
          pw.SizedBox(height: 24),
          _footer(),
        ],
      ),
    );
  }

  List<pw.Widget> _paragraphs(String text) => text
      .split('\n')
      .map((String line) => pw.Paragraph(
            text: line.isEmpty ? ' ' : line,
            style: const pw.TextStyle(fontSize: 12, lineSpacing: 2),
          ))
      .toList();

  pw.Widget _footer() => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: <pw.Widget>[
          pw.Divider(),
          pw.Text(
            'Generated by DocWriter',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
          ),
        ],
      );

  /// Opens the system print dialog.
  Future<void> printDoc(Doc doc) async {
    final Uint8List bytes = await buildPdf(doc);
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => bytes,
      name: fileNameFor(doc),
    );
  }

  /// Opens the system save / share sheet (Save to Files, Drive, email, ...).
  Future<void> shareDoc(Doc doc) async {
    final Uint8List bytes = await buildPdf(doc);
    await Printing.sharePdf(bytes: bytes, filename: fileNameFor(doc));
  }

  String fileNameFor(Doc doc) {
    final String raw = doc.displayTitle;
    final String safe =
        raw.replaceAll(RegExp(r'[^A-Za-z0-9 _-]'), '').trim().replaceAll(' ', '_');
    if (safe.isEmpty) return doc.isLetter ? 'letter.pdf' : 'document.pdf';
    return '$safe.pdf';
  }
}
