import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/doc.dart';

/// Turns a [Doc] into a PDF and hands it to the platform to print or share.
class PdfService {
  Future<Uint8List> buildPdf(Doc doc) async {
    final pw.Document pdf = pw.Document();
    final String title = doc.displayTitle;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        build: (pw.Context context) => <pw.Widget>[
          pw.Header(level: 0, text: title),
          pw.SizedBox(height: 12),
          ...doc.body.split('\n').map(
                (String line) => pw.Paragraph(
                  text: line.isEmpty ? ' ' : line,
                  style: const pw.TextStyle(fontSize: 12),
                ),
              ),
          pw.SizedBox(height: 24),
          pw.Divider(),
          pw.Paragraph(
            text: 'Generated by DocWriter',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  /// Opens the system print dialog.
  Future<void> printDoc(Doc doc) async {
    final Uint8List bytes = await buildPdf(doc);
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => bytes,
      name: fileNameFor(doc),
    );
  }

  /// Opens the system save / share sheet (Save to Files, Drive, email, ...).
  Future<void> shareDoc(Doc doc) async {
    final Uint8List bytes = await buildPdf(doc);
    await Printing.sharePdf(bytes: bytes, filename: fileNameFor(doc));
  }

  String fileNameFor(Doc doc) {
    final String raw = doc.title.trim().isEmpty ? 'document' : doc.title.trim();
    final String safe =
        raw.replaceAll(RegExp(r'[^A-Za-z0-9 _-]'), '').trim().replaceAll(' ', '_');
    return '${safe.isEmpty ? 'document' : safe}.pdf';
  }
}
